# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=30)),
                ('title_year', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(max_length=5000)),
                ('language', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('stars', models.CharField(max_length=100)),
                ('length_min', models.IntegerField()),
                ('rating_overall', models.DecimalField(decimal_places=3, max_digits=5)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
