# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0002_remove_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank='TRUE', max_length=5000),
        ),
    ]
