# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0008_auto_20170207_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=200),
        ),
    ]
