# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0015_auto_20170303_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='Wishlist',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='watchlist',
            new_name='wishlist',
        ),
    ]
