# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0016_auto_20170303_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='movie',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='movie',
            field=models.ManyToManyField(to='movielist.Movie'),
        ),
    ]
