# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0023_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist',
            field=models.BooleanField(),
        ),
    ]
