# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0024_auto_20170310_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('movie', models.ManyToManyField(to='movielist.Movie')),
            ],
        ),
    ]
