# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0026_auto_20170316_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='actor_name',
            new_name='name',
        ),
    ]
