# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0027_auto_20170316_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating_overall',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
