# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0028_auto_20170317_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seenlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('seenlist', models.BooleanField()),
                ('movie', models.ManyToManyField(to='movielist.Movie')),
            ],
        ),
    ]
