# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0029_seenlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seenlist',
            name='movie',
        ),
        migrations.AddField(
            model_name='seenlist',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movielist.Movie'),
            preserve_default=False,
        ),
    ]
