# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movielist', '0031_auto_20170321_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seenlist',
            name='user',
        ),
        migrations.AddField(
            model_name='seenlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
