# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0033_auto_20170321_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
