# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0034_auto_20170323_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seenlist',
            old_name='movie',
            new_name='movies',
        ),
    ]
