# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0037_auto_20170326_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
