# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0039_auto_20170326_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toseelist',
            name='toseelist',
        ),
    ]
