# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0040_remove_toseelist_toseelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movies',
        ),
        migrations.AddField(
            model_name='rating',
            name='movies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movielist.Movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
