# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0045_auto_20170328_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
